//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckCasher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckCasher.Resources.HomeWindow", typeof(HomeWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About CheckCasher.
        /// </summary>
        public static string AboutCheckCasher {
            get {
                return ResourceManager.GetString("AboutCheckCasher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2010 - EWeb Computing Solutions Inc. Website:http://CheckCasher.ewebcomputing.com.
        /// </summary>
        public static string Copyrightc2010EWebComputingSol {
            get {
                return ResourceManager.GetString("Copyrightc2010EWebComputingSol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Invoice.
        /// </summary>
        public static string CreateNewInvoice {
            get {
                return ResourceManager.GetString("CreateNewInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers/Billers.
        /// </summary>
        public static string CustomersBillers {
            get {
                return ResourceManager.GetString("CustomersBillers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Reports.
        /// </summary>
        public static string DailyReports {
            get {
                return ResourceManager.GetString("DailyReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due By Customer.
        /// </summary>
        public static string DueByCustomer {
            get {
                return ResourceManager.GetString("DueByCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due By Customer.
        /// </summary>
        public static string DueByCustomer1 {
            get {
                return ResourceManager.GetString("DueByCustomer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Billers.
        /// </summary>
        public static string ExportBillers {
            get {
                return ResourceManager.GetString("ExportBillers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Customers.
        /// </summary>
        public static string ExportCustomers {
            get {
                return ResourceManager.GetString("ExportCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Inventory.
        /// </summary>
        public static string ExportInventory {
            get {
                return ResourceManager.GetString("ExportInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Invoices.
        /// </summary>
        public static string ExportInvoices {
            get {
                return ResourceManager.GetString("ExportInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckCasher Help.
        /// </summary>
        public static string CheckCasherHelp {
            get {
                return ResourceManager.GetString("CheckCasherHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckCasher - CheckCasher.ewebcomputing.com.
        /// </summary>
        public static string CheckCasherCheckCasherewebcomput {
            get {
                return ResourceManager.GetString("CheckCasherCheckCasherewebcomput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice/Inventory.
        /// </summary>
        public static string InvoiceInventory {
            get {
                return ResourceManager.GetString("InvoiceInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Billers.
        /// </summary>
        public static string ManageBillers {
            get {
                return ResourceManager.GetString("ManageBillers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Customers.
        /// </summary>
        public static string ManageCustomers {
            get {
                return ResourceManager.GetString("ManageCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Inventory.
        /// </summary>
        public static string ManageInventory {
            get {
                return ResourceManager.GetString("ManageInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Invoices.
        /// </summary>
        public static string ManageInvoices {
            get {
                return ResourceManager.GetString("ManageInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales By Biller.
        /// </summary>
        public static string SalesByBiller {
            get {
                return ResourceManager.GetString("SalesByBiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales By Biller.
        /// </summary>
        public static string SalesByBiller1 {
            get {
                return ResourceManager.GetString("SalesByBiller1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales By Customer.
        /// </summary>
        public static string SalesByCustomer {
            get {
                return ResourceManager.GetString("SalesByCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales By Customer.
        /// </summary>
        public static string SalesByCustomer1 {
            get {
                return ResourceManager.GetString("SalesByCustomer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales By Products.
        /// </summary>
        public static string SalesByProducts {
            get {
                return ResourceManager.GetString("SalesByProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales By Products.
        /// </summary>
        public static string SalesByProducts1 {
            get {
                return ResourceManager.GetString("SalesByProducts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Reports.
        /// </summary>
        public static string WeeklyReports {
            get {
                return ResourceManager.GetString("WeeklyReports", resourceCulture);
            }
        }
    }
}
