//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IdDataErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdDataErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleDemo.Resources.IdDataErrors", typeof(IdDataErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_STATE_NOT_INIT.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("-10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_NO_NEXT_STATE.
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("-11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_CANNOT_DELETE_DESTINATION_IMAGE.
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("-12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_CANNOT_COPY_TO_DESTONATION.
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("-13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_FACE_IMAGE_NOT_FOUND.
        /// </summary>
        internal static string _14 {
            get {
                return ResourceManager.GetString("-14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_STATE_NOT_RECOGNIZED.
        /// </summary>
        internal static string _15 {
            get {
                return ResourceManager.GetString("-15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_USA_TEMPLATES_NOT_FOUND.
        /// </summary>
        internal static string _16 {
            get {
                return ResourceManager.GetString("-16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_WRONG_TEMPLATE_FILE.
        /// </summary>
        internal static string _17 {
            get {
                return ResourceManager.GetString("-17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_REGION_NOT_INIT.
        /// </summary>
        internal static string _18 {
            get {
                return ResourceManager.GetString("-18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_AUTO_DETECT_NOT_SUPPORTED.
        /// </summary>
        internal static string _19 {
            get {
                return ResourceManager.GetString("-19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_STATE_NOT_SUPORTED.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_COMPARE_NO_TEXT	.
        /// </summary>
        internal static string _20 {
            get {
                return ResourceManager.GetString("-20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_COMPARE_NO_BARCODE.
        /// </summary>
        internal static string _21 {
            get {
                return ResourceManager.GetString("-21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_COMPARE_BC_LIB_NOT_FOUND	.
        /// </summary>
        internal static string _22 {
            get {
                return ResourceManager.GetString("-22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_COMPARE_LICENSE_DONT_MATCH_BC_LIBRARY.
        /// </summary>
        internal static string _23 {
            get {
                return ResourceManager.GetString("-23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_DM_LIBRARY_NOT_FOUND.
        /// </summary>
        internal static string _24 {
            get {
                return ResourceManager.GetString("-24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_DM_LIBRARY_NOT_LOADED.
        /// </summary>
        internal static string _25 {
            get {
                return ResourceManager.GetString("-25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_DM_WM_NOT_FOUND.
        /// </summary>
        internal static string _26 {
            get {
                return ResourceManager.GetString("-26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_DM_WM_NOT_AUTHENTICATED.
        /// </summary>
        internal static string _27 {
            get {
                return ResourceManager.GetString("-27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_BAD_PARAM.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_NO_MATCH.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_FILE_OPEN.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_BAD_DESTINATION_FILE.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("-6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_FEATURE_NOT_SUPPORTED.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("-7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_COUNTRY_NOT_INIT.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("-8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ERR_NO_NEXT_COUNTRY.
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("-9", resourceCulture);
            }
        }
    }
}
