//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImageErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImageErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleDemo.Resources.ImageErrors", typeof(ImageErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMG ERR FILE OPEN.
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("-100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMG ERR BAD ANGLE.
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("-101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMG ERR BAD ANGLE.
        /// </summary>
        internal static string _102 {
            get {
                return ResourceManager.GetString("-102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMG ERR BAD DESTINATION	.
        /// </summary>
        internal static string _103 {
            get {
                return ResourceManager.GetString("-103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMG ERR SAVE TO FILE.
        /// </summary>
        internal static string _104 {
            get {
                return ResourceManager.GetString("-104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMG ERR FILE SAVE TO CLIPBOARD.
        /// </summary>
        internal static string _105 {
            get {
                return ResourceManager.GetString("-105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMG ERR FILE OPEN.
        /// </summary>
        internal static string _106 {
            get {
                return ResourceManager.GetString("-106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMG ERR FILE OPEN.
        /// </summary>
        internal static string _107 {
            get {
                return ResourceManager.GetString("-107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMG ERR COMB TYPE.
        /// </summary>
        internal static string _108 {
            get {
                return ResourceManager.GetString("-108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMG ERR BAD PARAM.
        /// </summary>
        internal static string _109 {
            get {
                return ResourceManager.GetString("-109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMG ERR BAD COLOR.
        /// </summary>
        internal static string _130 {
            get {
                return ResourceManager.GetString("-130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMG ERR BAD DPI.
        /// </summary>
        internal static string _131 {
            get {
                return ResourceManager.GetString("-131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_INTERNAL_IMAGE.
        /// </summary>
        internal static string _132 {
            get {
                return ResourceManager.GetString("-132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAD_IMAGE_DUMP.
        /// </summary>
        internal static string _133 {
            get {
                return ResourceManager.GetString("-133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAD_IMAGE_DIMENSIONS.
        /// </summary>
        internal static string _134 {
            get {
                return ResourceManager.GetString("-134", resourceCulture);
            }
        }
    }
}
