//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckCasher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Inventory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Inventory() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckCasher.Resources.Inventory", typeof(Inventory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Inventory.
        /// </summary>
        public static string AddInventory {
            get {
                return ResourceManager.GetString("AddInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string Individual {
            get {
                return ResourceManager.GetString("Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory1 {
            get {
                return ResourceManager.GetString("Inventory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item1 {
            get {
                return ResourceManager.GetString("Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        public static string ItemCode {
            get {
                return ResourceManager.GetString("ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No.
        /// </summary>
        public static string ItemNo {
            get {
                return ResourceManager.GetString("ItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Buy.
        /// </summary>
        public static string PriceBuy {
            get {
                return ResourceManager.GetString("PriceBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Buy.
        /// </summary>
        public static string PriceBuy1 {
            get {
                return ResourceManager.GetString("PriceBuy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Sell.
        /// </summary>
        public static string PriceSell {
            get {
                return ResourceManager.GetString("PriceSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Sell.
        /// </summary>
        public static string PriceSell1 {
            get {
                return ResourceManager.GetString("PriceSell1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Value.
        /// </summary>
        public static string UnitValue {
            get {
                return ResourceManager.GetString("UnitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Vendor1 {
            get {
                return ResourceManager.GetString("Vendor1", resourceCulture);
            }
        }
    }
}
